CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Lastname VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(10) NOT NULL,
    OtpCode VARCHAR(6),
    OtpExpiresAt TIMESTAMP
);